spring.application.name=app-users-ws

#server.port=0
spring.cloud.config.enabled=false



server.port=${PORT:0}
#eureka.client.service-url.defaultZone=http://192.168.1.250:8761/eureka
#eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.long}}

#spring.devtools.livereload.enabled=true
spring.devtools.restart.enabled=true
#hardcoded Ipaddress for checking in security
my.app.gateway.ip.address=172.25.48.1


#h2 database setting
#spring.h2.console.enabled=true
#spring.h2.console.settings.web-allow-others=true
#spring.h2.console.path=/h2-console
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=password
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

#postgresql datasource
spring.datasource.url=jdbc:postgresql://localhost/cloud
spring.datasource.username=postgres
spring.datasource.password=passw0rd
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#actuator settings
management.endpoints.web.exposure.include=*
management.endpoint.env.show-values=always
management.endpoint.env.access=unrestricted

