


spring.sql.init.mode=update
spring.graphql.graphiql.enabled=true

#spring.graphql.http.path=/graphql
#spring.graphql.websocket.path=/graphql

spring.graphql.cors.allowed-origins=http://localhost:3000,http://localhost:8080
spring.datasource.url=mongodb://localhost:27017/test
