
spring.data.mongodb.uri=mongodb://localhost:27017/test
spring.data.mongodb.auto-index-creation=true
server.port=8080

spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.auto-commit=true



